Update 2017-04-09-sutherland-benjelene.md
NBCLab/NBCLab.github.io pull request #255
Opened 2020-09-10 15:12 UTC by Benjelene

Hi @tsalo ! here is the new PR. Thank you!

2020-09-10 15:19 UTC, tsalo requested changes
There are minor problems with two of the fields you've updated. I have added code suggestions that you can either accept or emulate in a separate commit.

You can also automatically close specific issues with pull requests. There is an open issue about your profile (#245). Please add the phrase "Closes #245" to the first comment in the PR above to link the two.

2020-09-10 15:19 UTC, tsalo commented on team/_posts/2017-04-09-sutherland-benjelene.md
> +orcid:https://orcid.org/0000-0003-1721-9554
```suggestion
orcid: 0000-0003-1721-9554
```
You don't need the full URL, plus there should be a space after the field and before the value.

2020-09-10 15:19 UTC, tsalo commented on team/_posts/2017-04-09-sutherland-benjelene.md
> +researchgate:https://www.researchgate.net/profile/Benjelene_Sutherland
```suggestion
researchgate: Benjelene_Sutherland
```
You just need the username (i.e., the last part of the URL).

2020-09-11 14:35 UTC, tsalo commented on team/_posts/2017-04-09-sutherland-benjelene.md
> +orcid:0000-0003-1721-9554
We actually want this space.

2020-09-11 14:35 UTC, tsalo commented on team/_posts/2017-04-09-sutherland-benjelene.md
> +researchgate:Benjelene_Sutherland
We want this space too.

2020-09-11 14:39 UTC, Benjelene reviewed
Good morning @tsalo !

I hope all is well. Is this okay? Thank you!

2020-09-11 14:41 UTC, tsalo commented
The profile looks good. The only thing left to do is update your original comment (not the title, but the first box you see on this page) with the term "Closes #245".

2020-09-11 14:46 UTC, merged