Rpintosl patch 2
NBCLab/NBCLab.github.io pull request #257
Opened 2020-09-23 13:49 UTC by rpintosl

2020-09-23 14:03 UTC, tsalo requested changes
There are a few changes that need to be made.
1. The dates in the team filenames don't correspond to when the person joined the lab. They are just used to define the order of the lab members on the Team page. First the PI, then the co-PI, then research associates, then post-docs, then grad students, etc. Your file's date should be "2017-04-09" as a second-year grad student.
2. There is a conflict with your photo. You need to resolve this by choosing one version of the photo over another. You should be able to do it on GitHub Desktop or from the command-line. I would recommend updating from the main repository on your laptop with GitHub Desktop.

2020-09-23 14:03 UTC, tsalo commented on team/_posts/2020-08-03-pintos-lobo-rosario.md
> +scholar: https://scholar.google.com/citations?hl=en&user=gLjcvmkAAAAJ&view_op=list_works&gmla=AJsN-F4S_3SlZ0KhZYLg1M5DKE9LmTFNfUhCM3K_zXN3at0XBy5WVKmPw0RQgfikViKbWNCFH-EvF6zAxr6QcScCYuTV8H-SAQ
```suggestion
scholar: gLjcvmkAAAAJ
```
Just provide the user ID.

2020-09-23 17:16 UTC, tsalo commented on team/_posts/2017-05-09-pintos-lobo-rosario.md
> +scholar: https://scholar.google.com/citations?hl=en&user=gLjcvmkAAAAJ&view_op=list_works&gmla=AJsN-F4S_3SlZ0KhZYLg1M5DKE9LmTFNfUhCM3K_zXN3at0XBy5WVKmPw0RQgfikViKbWNCFH-EvF6zAxr6QcScCYuTV8H-SAQ
```suggestion
scholar: gLjcvmkAAAAJ
```
Just the ID- not the full URL.

2020-09-23 17:18 UTC, tsalo requested changes
There are a bunch of new files that should be removed, like `posters/_posts/.Rhistory` and `team/_posts/.Rhistory`. Also, the folder `team/_posts/_site/` should be removed.

Finally, please look at the suggested change to the Google Scholar link.

2020-09-23 17:35 UTC, rpintosl commented
@tsalo I removed the two files (posters/_posts/.Rhistory and team/_posts/.Rhistory, and accepted your suggested change on google scholar. I can't figure out how to remove an entire folder (team/_posts/_site/).

2020-09-24 19:09 UTC, rpintosl commented
![20171018203609_IMG_0356](https://user-images.githubusercontent.com/38221317/94188785-de28ca80-fe77-11ea-9418-63a7bbd033aa.JPG)

2020-09-24 19:27 UTC, rpintosl commented
@tsalo I *think* I successfully updated the picture? I committed to rpintosl-patch-2

2020-09-24 19:29 UTC, tsalo commented
I'm not seeing it. Are you referring to the comment where you posted the picture above?

2020-09-24 19:33 UTC, rpintosl commented
> I'm not seeing it. Are you referring to the comment where you posted the picture above?

@tsalo No, sorry. That was just me checking to see if it worked. I committed from Github desktop but I just saw your message saying to upload directly on Github. Where in Github should I upload?

2020-09-24 19:38 UTC, tsalo commented
If you committed in GitHub Desktop you just need to push to GitHub. I'd go with that instead of duplicating effort by adding the file on the website.

2020-09-28 19:08 UTC, tsalo approved these changes
Everything looks great! Thanks!

2020-09-28 19:09 UTC, merged