Update CV link
NBCLab/NBCLab.github.io pull request #289
Opened 2021-03-03 15:44 UTC by 62442katieb

I accidentally broke my CV link. 🙃 Should be good-to-go now.

2021-03-03 15:57 UTC, tsalo requested changes
Not sure if the figure already exists under a different name or if you need to add it.

2021-03-03 15:57 UTC, tsalo commented on posters/_posts/2019-06-12-bottenhorn-physics-poster.md
> +image: /assets/images/posters/2019-06-12-bottenhorn-physics-poster.png
This image doesn't exist.

2021-03-07 17:52 UTC, tsalo commented
The poster page you're adding seems to be a mashup of ["Quantitative comparison of functional decoding approaches across meta-analytic frameworks"](https://nbclab.github.io/posters/bottenhorn-decoding-poster) and ["Large-scale brain networks underlying domain-specific memory, intelligence, and academic performance"](https://nbclab.github.io/posters/bottenhorn-networks-ohbm). The title and image seem to be for the latter, while the author list, fulltext, and abstract match the former.

2021-03-08 14:16 UTC, 62442katieb commented
I'm on it. Looks like I just hadn't finished updating the poster page and it was abandoned. 😢 Will fix later today

2021-03-08 16:27 UTC, 62442katieb commented
Turns out it was actually a weird duplicate poster page. Fixed! (And GitHub link updated!)

2021-03-08 16:30 UTC, merged